name: Build Packages

on:
  push:
  workflow_dispatch:
jobs:
  build_and_publish:
    runs-on: windows-latest
    env:
      BUILD_TYPE: STAGE
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: global.json
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build packages
        run: .\build.ps1
      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts