name: Build Packages

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build project
        run: dotnet build ./GroupDocs.Viewer.UI.sln